### ISSUE TITLE
Nice Presentation Screen and thumbnail preview

### ISSUE THREAD

**Issue by anubhab91** [Schnouki/pympress#23]
I have just installed `pympress` (from the tarball), and two things come in to mind:
1. A full screen presentation window with a progress bar 
2. Using thumbnail previews to all slides

What do you think?

**Comment by Schnouki** [comment]
Hi, this repo is no longer maintained. Please have a look at https://github.com/Cimbaly/pympress instead.

**Comment by anubhab91** [comment]
404!
That'd be https://github.com/Cimbali/pympress

**Comment by Schnouki** [comment]
Right, sorry! :)
