### ISSUE TITLE
unmantained project?

### ISSUE THREAD

**Issue by ousia** [Schnouki/pympress#26]
@Schnouki,

many thanks for your code and your great tool.

It seems that your interest focuses now in other projects: no commits since a long time, not even new issues and pympress.org doesn’t work anymore.

How about adding a README.md file to explain that the project is deprecated and that further development is done by @Cimbali?

I may write a PR myself, if you want (but only if you merge it).

**Comment by Schnouki** [comment]
Yep, I think it's more than time for me to move on for good...

@Cimbali, first let me thank you **a lot** for everything you did on pympress. It's huge, and amazing. Congrats!

Now, I can either add a README.md with a short explanation and a link to your repo, or I can transfer the whole repo, and github.com/Schnouki/pympress will then redirect to your repo. What would you prefer?

**Comment by Cimbali** [comment]
Hi @Schnouki! I'm just happy to make the project live on ;)

For how to acknowledge the new repo, I think transferring is better due to how the search works on github, but I'm fine with the README way too. In any case credit for your work is present and it will remain that way.

**Comment by Schnouki** [comment]
Thanks @Cimbali :) I'll transfer the repo then! And thanks again for your awesome work on pympress.

**Comment by Schnouki** [comment]
Aaand I can't transfer because @Cimbali /pympress already exists... Not sure what to do now :/

**Comment by Cimbali** [comment]
I sent an email to support to know what is feasible. If they say nothing can be done, we can always fallback to the README way.

**Comment by Cimbali** [comment]
Apparently you can just ask support to make Cimbali/pympress the parent repo in the network. After that your repo will look like a fork instead of the base.

**Comment by Schnouki** [comment]
Thanks, I've asked support to do just that (and linked to this discussion -- hi to anyone reading! 👋)

**Comment by Cimbali** [comment]
It's already done apparently. Thanks @Schnouki!

**Comment by Schnouki** [comment]
\o/
